name: Shell commands

on: [push]

jobs:
  run-shell-commands: 
    runs-on: ubuntu-latest
    steps:
      - name: echos a string
        run: echo "Hello World!"
      - name: multi-line script
        run: |
          node -v
          npm -v 
          echo "This is the third shell line script."
      - name: Python command
        run: |
          import platform
          print(platform.processor())
        shell: python